### ISSUE TITLE
ReleaseType no longer supported in pulumi-kubernetes

### ISSUE THREAD

**Issue by viveklak** [joeduffy/pulumi-go-helmbase#1]
ReleaseType was removed in https://github.com/pulumi/pulumi-kubernetes/pull/1805/files pulumi-kubernetes. We can either generate an overlay type with appropriate type annotations locally or we need to resurrect the above type.

**Comment by rshade** [comment]
Since its a trap door into the helm chart can we just use ReleaseArgs? I was looking into https://github.com/pulumi/pulumi-kubernetes-ingress-nginx/issues/4, and ran into the same issue when updating the sdk.

**Comment by viveklak** [comment]
> Since its a trap door into the helm chart can we just use ReleaseArgs? I was looking into [pulumi/pulumi-kubernetes-ingress-nginx#4](https://github.com/pulumi/pulumi-kubernetes-ingress-nginx/issues/4), and ran into the same issue when updating the sdk.

The reason why we can't use ReleaseArgs directly is because it doesn't have the `pulumi` type annotations as noted in https://github.com/pulumi/pulumi/issues/8112
